#include "simbridge/dds_bridge.hpp"

#include <dds/dds.h>

#include <atomic>
#include <vector>

#include "simbridge/messages.hpp"
#include "simbridge_types.h"  // generated by idlc from idl/simbridge_types.idl

namespace simbridge {

namespace {

dds_entity_t check(dds_entity_t rc, const char* what) {
    if (rc < 0) throw DdsError(std::string("DDS ") + what + " failed: " + dds_strretcode(-rc));
    return rc;
}

// RAII owner for a dds_qos_t.
struct Qos {
    Qos() : q(dds_create_qos()) {}
    ~Qos() { dds_delete_qos(q); }
    Qos(const Qos&) = delete;
    Qos& operator=(const Qos&) = delete;
    dds_qos_t* q;
};

simbridge_dds_Vec3 to_dds(const Vec3& v) { return simbridge_dds_Vec3{v.x, v.y, v.z}; }

}  // namespace

struct DdsBridge::Impl {
    MessageBus& bus;
    DdsBridgeOptions opts;
    dds_entity_t participant = 0;
    dds_entity_t state_writer = 0;
    dds_entity_t detection_writer = 0;
    dds_entity_t command_reader = 0;
    std::vector<SubscriptionId> subs;
    std::atomic<uint64_t> states{0}, detections{0}, commands{0}, errors{0};

    Impl(MessageBus& b, DdsBridgeOptions o) : bus(b), opts(o) {}

    ~Impl() {
        for (auto id : subs) bus.unsubscribe(id);
        if (participant > 0) dds_delete(participant);  // deletes topics, writers and readers too
    }

    void open() {
        participant = check(dds_create_participant(opts.domain_id, nullptr, nullptr), "create_participant");

        Qos state_qos;  // latest state per entity, kept for late joiners
        dds_qset_reliability(state_qos.q, DDS_RELIABILITY_RELIABLE, DDS_SECS(1));
        dds_qset_durability(state_qos.q, DDS_DURABILITY_TRANSIENT_LOCAL);
        dds_qset_history(state_qos.q, DDS_HISTORY_KEEP_LAST, 1);

        Qos event_qos;  // detections: every report delivered, nothing replayed
        dds_qset_reliability(event_qos.q, DDS_RELIABILITY_RELIABLE, DDS_SECS(1));
        dds_qset_durability(event_qos.q, DDS_DURABILITY_VOLATILE);
        dds_qset_history(event_qos.q, DDS_HISTORY_KEEP_LAST, 256);

        Qos command_qos;  // newest command per entity wins
        dds_qset_reliability(command_qos.q, DDS_RELIABILITY_RELIABLE, DDS_SECS(1));
        dds_qset_durability(command_qos.q, DDS_DURABILITY_VOLATILE);
        dds_qset_history(command_qos.q, DDS_HISTORY_KEEP_LAST, 1);

        if (opts.publish_state) {
            const dds_entity_t topic = check(
                dds_create_topic(participant, &simbridge_dds_EntityState_desc, dds_topics::kEntityState, nullptr, nullptr),
                "create_topic(EntityState)");
            state_writer = check(dds_create_writer(participant, topic, state_qos.q, nullptr), "create_writer(EntityState)");
            subs.push_back(bus.subscribe<EntityState>(topics::kEntityState, [this](const EntityState& s) { write(s); }));
        }
        if (opts.publish_detections) {
            const dds_entity_t topic = check(
                dds_create_topic(participant, &simbridge_dds_Detection_desc, dds_topics::kDetection, nullptr, nullptr),
                "create_topic(Detection)");
            detection_writer =
                check(dds_create_writer(participant, topic, event_qos.q, nullptr), "create_writer(Detection)");
            subs.push_back(bus.subscribe<Detection>(topics::kDetection, [this](const Detection& d) { write(d); }));
        }
        if (opts.accept_commands) {
            const dds_entity_t topic = check(dds_create_topic(participant, &simbridge_dds_VehicleCommand_desc,
                                                              dds_topics::kVehicleCommand, nullptr, nullptr),
                                             "create_topic(VehicleCommand)");
            command_reader =
                check(dds_create_reader(participant, topic, command_qos.q, nullptr), "create_reader(VehicleCommand)");
        }
    }

    void write(const EntityState& s) {
        simbridge_dds_EntityState m{};
        m.id = s.id;
        m.name = const_cast<char*>(s.name.c_str());  // only read during dds_write
        m.t = s.t;
        m.pos = to_dds(s.pos);
        m.vel = to_dds(s.vel);
        m.heading_rad = s.heading_rad;
        m.speed_mps = s.speed_mps;
        if (dds_write(state_writer, &m) < 0) {
            ++errors;
            return;
        }
        ++states;
    }

    void write(const Detection& d) {
        simbridge_dds_Detection m{};
        m.sensor_id = d.sensor_id;
        m.host_id = d.host_id;
        m.target_id = d.target_id;
        m.t = d.t;
        m.range_m = d.range_m;
        m.bearing_rad = d.bearing_rad;
        if (dds_write(detection_writer, &m) < 0) {
            ++errors;
            return;
        }
        ++detections;
    }

    std::size_t poll() {
        if (command_reader <= 0) return 0;
        constexpr int kBatch = 32;
        std::size_t delivered = 0;
        for (;;) {
            void* samples[kBatch] = {};
            dds_sample_info_t infos[kBatch];
            const int n = dds_take(command_reader, samples, infos, kBatch, kBatch);
            if (n < 0) throw DdsError(std::string("DDS take failed: ") + dds_strretcode(-n));
            if (n == 0) break;
            // Copy out before returning the loan, then publish without holding DDS memory.
            std::vector<VehicleCommand> batch;
            batch.reserve(static_cast<std::size_t>(n));
            for (int i = 0; i < n; ++i) {
                if (!infos[i].valid_data) continue;  // dispose / unregister notifications
                const auto* m = static_cast<const simbridge_dds_VehicleCommand*>(samples[i]);
                VehicleCommand c;
                c.entity_id = m->entity_id;
                c.t = m->t;
                c.heading_rad = m->heading_rad;
                c.speed_mps = m->speed_mps;
                batch.push_back(c);
            }
            dds_return_loan(command_reader, samples, n);
            for (const auto& c : batch) bus.publish(topics::kVehicleCommand, c);
            delivered += batch.size();
            if (n < kBatch) break;
        }
        commands += delivered;
        return delivered;
    }
};

DdsBridge::DdsBridge(MessageBus& bus, DdsBridgeOptions options) : impl_(std::make_unique<Impl>(bus, options)) {
    impl_->open();  // on failure ~Impl releases whatever was created
}

DdsBridge::~DdsBridge() = default;

std::size_t DdsBridge::poll_commands() { return impl_->poll(); }

DdsBridgeStats DdsBridge::stats() const {
    return DdsBridgeStats{impl_->states.load(), impl_->detections.load(), impl_->commands.load(),
                          impl_->errors.load()};
}

uint32_t DdsBridge::domain_id() const { return impl_->opts.domain_id; }

}  // namespace simbridge
